# Example: New Laptop Configuration
# This demonstrates how easy it is to create a new system configuration
# using the modular structure.

{ config, pkgs, ... }:

{
  imports = [
    # Import all common modules with a single line
    ../../modules/common
    
    # Add laptop-specific settings
    ../../modules/hardware/laptop.nix
    
    # Add user account
    ../../modules/users/chris.nix
    
    # Optional: Add printing if needed
    # ../../modules/common/printing.nix
    
    # Hardware-specific (generated by nixos-generate-config)
    ./hardware-configuration.nix
    
    # Choose your desktop environment
    ../../desktops/gnome.nix
    # OR: ../../desktops/niri.nix
    # OR: ../../desktops/hyprland.nix
    # OR: ../../desktops/plasma.nix
  ];

  # System-specific settings
  networking.hostName = "new-laptop";
  networking.hostId = "12345678";  # Generate with: head -c 8 /etc/machine-id
  
  # Optional: Override auto-upgrade schedule
  system.autoUpgrade = {
    enable = true;
    dates = "weekly";
  };

  # Add any system-specific packages
  environment.systemPackages = with pkgs; [
    # your-special-package
  ];

  system.stateVersion = "24.11";
}
