name: Update flake.lock

on:
  schedule:
    - cron: "0 2 * * *"

  pull_request:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v20

      - run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update flake.lock
          branch: main
          file_pattern: flake.lock
          commit_author: GitHub Actions <actions@github.com>
